server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comma_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${custom.dev-mysql-username}
    password: ${custom.dev-mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always