server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  datasource:
    url: com.mysql.cj.jdbc.Driver
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
custom:
  site:
    name: gamedragons
    baseUrl: "http://localhost:${server.port}"
#  tempDirPath: c:/gamedragons/gamedragons_dev/temp
#  genFile:
#    dirPath: c:/gamedragons/gamedragons_dev