spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    sessions: STATELESS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
    token:
      access-expiration-time: 60000
      refresh-expiration-time: 604800000
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    com.bitharmony.comma: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  tossPayments:
    widget:
      clientKey: test_ck_5OWRapdA8dmGZpoK9jpA3o1zEqZK
      secretKey: ON_SECRET