ncp:
  image-credentials:
    access-key: q6YAPX1p8y3N8UP6DTCS
    secret-key: uUbKCAFycuDc6vFinZCnEAOI9y1De6mVTtS4vOHY
  music-credentials:
    access-key: 2q5W24I2fb0XvHYe20oL
    secret-key: tmkHuCrqgY2Xi7TB7mdYxaj7S9bitgAV6u9Wi8Cc
  s3:
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    stack: false
    image-bucket: album-image
    music-bucket: album-music
    music-path: music/input
  image-optimizer:
    cdn: https://kv6d2rdb2209.edge.naverncp.com/GSctnLFiOr
    query-string: ?type=f&w=300&h=300&ttype=jpg