name: work-1
on:
  push:
    branches:
      - ci_cd
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"